<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PACOCH8" ignored="0" name="Test" tests="9" failures="2" timestamp="2019-10-08T15:09:54 IST" time="0.12" errors="0">
  <testcase name="Test1" time="0.015" classname="com.qa.crm.TestNG.FailedRetryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.qa.crm.TestNG.FailedRetryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.qa.crm.TestNG.FailedRetryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.qa.crm.TestNG.FailedRetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.crm.TestNG.FailedRetryTest.Test1(FailedRetryTest.java:11)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="com.qa.crm.TestNG.FailedRetryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.qa.crm.TestNG.FailedRetryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="com.qa.crm.TestNG.FailedRetryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.qa.crm.TestNG.FailedRetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.crm.TestNG.FailedRetryTest.Test2(FailedRetryTest.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="com.qa.crm.TestNG.FailedRetryTest"/>
</testsuite> <!-- Test -->
